version: '3.8'

services:
  node-app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - MONGO_URL=mongodb://mongo:27017/authDB
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=authDB
    depends_on:
      - mongo
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo: 
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: authDB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mongo-data:
  mysql-data: 